volumes:
    mariadb:
      driver_opts:
        o: bind
        device: /home/esalmela/data/mariadb
        
networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        build:
            context: .
            dockerfile: requirements/mariadb/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - ../.env
        restart: always
