volumes:
    wordpress:
      driver_opts:
        type: none
        o: bind
        device: /home/esalmela/data/wordpress
    mariadb:
      driver_opts:
        type: none
        o: bind
        device: /home/esalmela/data/mariadb
        
networks:
    inception:
        name: inception
        driver: bridge

services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: requirements/nginx/Dockerfile
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress:/var/www/html
        env_file:
            - ../.env
        networks:
            - inception
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: .
            dockerfile: requirements/wordpress/Dockerfile
        depends_on:
            - mariadb
        volumes:
            - wordpress:/var/www/html
        networks:
            - inception
        env_file:
            - ../.env
        restart: always

    mariadb:
        container_name: mariadb
        build:
            context: .
            dockerfile: requirements/mariadb/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - ../.env
        restart: always
