volumes:
    mariadb_data:
        name: mariadb_data
        driver: local
        driver_opts:
            type: none
            device: /home/esalmela/data/mariadb
            o: bind

networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        build:
            context: .
            dockerfile: requirements/mariadb/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - ../.env
        restart: always
