volumes:
    mariadb_data:

networks:
    inception:
        name: inception
        driver: bridge

services:
    mariadb:
        container_name: mariadb
        build:
            context: .
            dockerfile: requirements/mariadb/Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - /home/esalmela/data/mariadb:/var/lib/mysql
        networks:
            - inception
        env_file:
            - ../.env
        restart: always
